export const PAYMENT_INTENT_CREATE= 'PAYMENT_INTENT_CREATE'
export const PAYMENT_INTENT_SUCCESS= 'PAYMENT_INTENT_SUCCESS'
export const PAYMENT_INTENT_FAIL= 'PAYMENT_INTENT_FAIL'
export const PAYMENT_INTENT_RESET = 'PAYMENT_INTENT_RESET'