export const ZIP_VALIDATE_REQUEST = 'ZIP_VALIDATE_REQUEST'
export const ZIP_VALIDATE_SUCCESS = 'ZIP_VALIDATE_SUCCESS'
export const ZIP_VALIDATE_FAIL = 'ZIP_VALIDATE_FAIL'
export const ZIP_VALIDATE_RESET = 'ZIP_VALIDATE_RESET'